CREATE TABLE BOOK (

ID int auto_increment PRIMARY KEY,

TITLE VARCHAR(255) NOT NULL
);
INSERT INTO BOOK(TITLE) VALUES ('Getting String Web1');
INSERT INTO BOOK(TITLE) VALUES ('Getting String Web2');
INSERT INTO BOOK(TITLE) VALUES ('Getting String Web3');
INSERT INTO BOOK(TITLE) VALUES ('Getting String Web4');
INSERT INTO BOOK(TITLE) VALUES ('Getting String Web5');
INSERT INTO BOOK(TITLE) VALUES ('Getting String Web6');
INSERT INTO BOOK(TITLE) VALUES ('Getting String Web7');
INSERT INTO BOOK(TITLE) VALUES ('Getting String Web8');
INSERT INTO BOOK(TITLE) VALUES ('Getting String Web9');
INSERT INTO BOOK(TITLE) VALUES ('Getting String Web10');
INSERT INTO BOOK(TITLE) VALUES ('Getting String Web11');
INSERT INTO BOOK(TITLE) VALUES ('Getting String Web12');
INSERT INTO BOOK(TITLE) VALUES ('Getting String Web13');
INSERT INTO BOOK(TITLE) VALUES ('Getting String Web14');
INSERT INTO BOOK(TITLE) VALUES ('Getting String Web15');
INSERT INTO BOOK(TITLE) VALUES ('Getting String Web16');
INSERT INTO BOOK(TITLE) VALUES ('Getting String Web17');
INSERT INTO BOOK(TITLE) VALUES ('Getting String Web18');
INSERT INTO BOOK(TITLE) VALUES ('Getting String Web19');
INSERT INTO BOOK(TITLE) VALUES ('Getting String Web20');
INSERT INTO BOOK(TITLE) VALUES ('Getting String Web21');
INSERT INTO BOOK(TITLE) VALUES ('Getting String Web22');
INSERT INTO BOOK(TITLE) VALUES ('Getting String Web23');
INSERT INTO BOOK(TITLE) VALUES ('Getting String Web24');
INSERT INTO BOOK(TITLE) VALUES ('Getting String Web25');
INSERT INTO BOOK(TITLE) VALUES ('Getting String Web26');
INSERT INTO BOOK(TITLE) VALUES ('Getting String Web27');
INSERT INTO BOOK(TITLE) VALUES ('Getting String Web28');
INSERT INTO BOOK(TITLE) VALUES ('Getting String Web29');
INSERT INTO BOOK(TITLE) VALUES ('Getting String Web30');
INSERT INTO BOOK(TITLE) VALUES ('Getting String Web31');

SELECT * FROM BOOK